export const voiceData = [
  {
    language: "American English",
    name: "af_heart",
    displayName: "Sarah (American Female)",
    traits: "🚺❤️",
    targetQuality: "A",
    trainingDuration: "",
    overallGrade: "A",
  },
  {
    language: "American English",
    name: "af_alloy",
    displayName: "Emily (American Female)",
    traits: "🚺",
    targetQuality: "B",
    trainingDuration: "MM minutes",
    overallGrade: "C",
  },
  {
    language: "American English",
    name: "af_aoede",
    displayName: "Madison (American Female)",
    traits: "🚺",
    targetQuality: "B",
    trainingDuration: "H hours",
    overallGrade: "C+",
  },
  {
    language: "American English",
    name: "af_bella",
    displayName: "Bella (American Female)",
    traits: "🚺🔥",
    targetQuality: "A",
    trainingDuration: "HH hours",
    overallGrade: "A-",
  },
  {
    language: "American English",
    name: "af_jessica",
    displayName: "Jessica (American Female)",
    traits: "🚺",
    targetQuality: "C",
    trainingDuration: "MM minutes",
    overallGrade: "D",
  },
  {
    language: "American English",
    name: "af_kore",
    displayName: "Kora (American Female)",
    traits: "🚺",
    targetQuality: "B",
    trainingDuration: "H hours",
    overallGrade: "C+",
  },
  {
    language: "American English",
    name: "af_nicole",
    displayName: "Nicole (American Female)",
    traits: "🚺🎧",
    targetQuality: "B",
    trainingDuration: "HH hours",
    overallGrade: "B-",
  },
  {
    language: "American English",
    name: "af_nova",
    displayName: "Nova (American Female)",
    traits: "🚺",
    targetQuality: "B",
    trainingDuration: "MM minutes",
    overallGrade: "C",
  },
  {
    language: "American English",
    name: "af_river",
    displayName: "River (American Female)",
    traits: "🚺",
    targetQuality: "C",
    trainingDuration: "MM minutes",
    overallGrade: "D",
  },
  {
    language: "American English",
    name: "af_sarah",
    displayName: "Laura (American Female)",
    traits: "🚺",
    targetQuality: "B",
    trainingDuration: "H hours",
    overallGrade: "C+",
  },
  {
    language: "American English",
    name: "af_sky",
    displayName: "Skylar (American Female)",
    traits: "🚺",
    targetQuality: "B",
    trainingDuration: "M minutes 🤏",
    overallGrade: "C-",
  },
  {
    language: "American English",
    name: "am_adam",
    displayName: "Adam (American Male)",
    traits: "🚹",
    targetQuality: "D",
    trainingDuration: "H hours",
    overallGrade: "F+",
  },
  {
    language: "American English",
    name: "am_echo",
    displayName: "Ethan (American Male)",
    traits: "🚹",
    targetQuality: "C",
    trainingDuration: "MM minutes",
    overallGrade: "D",
  },
  {
    language: "American English",
    name: "am_eric",
    displayName: "Eric (American Male)",
    traits: "🚹",
    targetQuality: "C",
    trainingDuration: "MM minutes",
    overallGrade: "D",
  },
  {
    language: "American English",
    name: "am_fenrir",
    displayName: "Felix (American Male)",
    traits: "🚹",
    targetQuality: "B",
    trainingDuration: "H hours",
    overallGrade: "C+",
  },
  {
    language: "American English",
    name: "am_liam",
    displayName: "Liam (American Male)",
    traits: "🚹",
    targetQuality: "C",
    trainingDuration: "MM minutes",
    overallGrade: "D",
  },
  {
    language: "American English",
    name: "am_michael",
    displayName: "Michael (American Male)",
    traits: "🚹",
    targetQuality: "B",
    trainingDuration: "H hours",
    overallGrade: "C+",
  },
  {
    language: "American English",
    name: "am_onyx",
    displayName: "Oliver (American Male)",
    traits: "🚹",
    targetQuality: "C",
    trainingDuration: "MM minutes",
    overallGrade: "D",
  },
  {
    language: "American English",
    name: "am_puck",
    displayName: "Peter (American Male)",
    traits: "🚹",
    targetQuality: "B",
    trainingDuration: "H hours",
    overallGrade: "C+",
  },
  {
    language: "American English",
    name: "am_santa",
    displayName: "Nick (American Male)",
    traits: "🚹",
    targetQuality: "C",
    trainingDuration: "M minutes 🤏",
    overallGrade: "D-",
  },
  {
    language: "British English",
    name: "bf_alice",
    displayName: "Alice (British Female)",
    traits: "🚺",
    targetQuality: "C",
    trainingDuration: "MM minutes",
    overallGrade: "D",
  },
  {
    language: "British English",
    name: "bf_emma",
    displayName: "Emma (British Female)",
    traits: "🚺",
    targetQuality: "B",
    trainingDuration: "HH hours",
    overallGrade: "B-",
  },
  {
    language: "British English",
    name: "bf_isabella",
    displayName: "Isabella (British Female)",
    traits: "🚺",
    targetQuality: "B",
    trainingDuration: "MM minutes",
    overallGrade: "C",
  },
  {
    language: "British English",
    name: "bf_lily",
    displayName: "Lily (British Female)",
    traits: "🚺",
    targetQuality: "C",
    trainingDuration: "MM minutes",
    overallGrade: "D",
  },
  {
    language: "British English",
    name: "bm_daniel",
    displayName: "Daniel (British Male)",
    traits: "🚹",
    targetQuality: "C",
    trainingDuration: "MM minutes",
    overallGrade: "D",
  },
  {
    language: "British English",
    name: "bm_fable",
    displayName: "Frederick (British Male)",
    traits: "🚹",
    targetQuality: "B",
    trainingDuration: "MM minutes",
    overallGrade: "C",
  },
  {
    language: "British English",
    name: "bm_george",
    displayName: "George (British Male)",
    traits: "🚹",
    targetQuality: "B",
    trainingDuration: "MM minutes",
    overallGrade: "C",
  },
  {
    language: "British English",
    name: "bm_lewis",
    displayName: "Lewis (British Male)",
    traits: "🚹",
    targetQuality: "C",
    trainingDuration: "H hours",
    overallGrade: "D+",
  },
];
